version: 2
# registries:
#   artifactory:
#     type: npm-registry
#     url: https://sixriver.jfrog.io/sixriver/api/npm/npm-local/
#     username: 6rs-machine
#     password: ${{secrets.ARTIFACTORY_TOKEN}}
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    # groups:
    #   go-everything:
    #     patterns:
    #       - "*"
    multi-ecosystem-group: everything
  - package-ecosystem: "npm"
    directory: "/internal/ts-compat/" # Location of package manifests
    schedule:
      interval: "monthly"
    versioning-strategy: increase
    # registries:
    #   - artifactory
    # groups:
    #   npm-ts-compat-everything:
    #     patterns:
    #       - "*"
    multi-ecosystem-group: everything

multi-ecosystem-groups:
  everything:
    schedule:
      interval: "monthly"
