{
 "title": "mmmbbb",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Create/Delete",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(mmmbbb_create_subscription_duration_count)) by (outcome)",
     "legendFormat": "+sub {{outcome}}"
    },
    {
     "expr": "sum(increase(mmmbbb_create_topic_duration_count)) by (outcome)",
     "legendFormat": "+topic {{outcome}}"
    },
    {
     "expr": "sum(increase(mmmbbb_delete_subscription_duration_count)) by (outcome)",
     "legendFormat": "-sub {{outcome}}"
    },
    {
     "expr": "sum(increase(mmmbbb_delete_topic_duration_count)) by (outcome)",
     "legendFormat": "-topic {{outcome}}"
    }
   ]
  },
  {
   "title": "Service Runs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(mmmbbb_deadletter_deliveries_duration_count)) by (outcome)",
     "legendFormat": "deadletter {{outcome}}"
    },
    {
     "expr": "sum(increase(mmmbbb_prune_completed_deliveries_duration_count)) by (outcome)",
     "legendFormat": "prune:delivs {{outcome}}"
    },
    {
     "expr": "sum(increase(mmmbbb_prune_completed_messages_duration_count)) by (outcome)",
     "legendFormat": "prune:msgs {{outcome}}"
    },
    {
     "expr": "sum(increase(mmmbbb_prune_deleted_subscription_deliveries_duration_count)) by (outcome)",
     "legendFormat": "prune:delsubdelivs {{outcome}}"
    },
    {
     "expr": "sum(increase(mmmbbb_prune_expired_deliveries_duration_count)) by (outcome)",
     "legendFormat": "prune:expdelivs {{outcome}}"
    },
    {
     "expr": "sum(increase(mmmbbb_prune_deleted_topics_duration_count)) by (outcome)",
     "legendFormat": "prune:deltopics {{outcome}}"
    },
    {
     "expr": "sum(increase(mmmbbb_prune_deleted_subscriptions_duration_count)) by (outcome)",
     "legendFormat": "prune:delsubs {{outcome}}"
    },
    {
     "expr": "sum(increase(mmmbbb_prune_expired_subscriptions_duration_count)) by (outcome)",
     "legendFormat": "prune:expsubs {{outcome}}"
    }
   ]
  },
  {
   "title": "Publishing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(mmmbbb_published_messages_duration_count)) by (outcome)",
     "legendFormat": "pub {{outcome}}"
    },
    {
     "expr": "sum(increase(mmmbbb_published_messages_num_enqueued)) ",
     "legendFormat": "msgs"
    },
    {
     "expr": "sum(increase(mmmbbb_published_messages_num_enqueued)) by (outcome)",
     "legendFormat": "delivs"
    }
   ]
  },
  {
   "title": "Publish Timing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(mmmbbb_published_messages_duration_sum)) by (outcome) / sum(increase(mmmbbb_published_messages_duration_count)) by (outcome)",
     "legendFormat": "per {{outcome}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(mmmbbb_published_messages_duration_bucket)) by (le,outcome))",
     "legendFormat": "p95 {{outcome}}"
    },
    {
     "expr": "sum(rate(mmmbbb_published_messages_duration_count)) by (outcome)",
     "legendFormat": "rate {{outcome}}"
    }
   ]
  },
  {
   "title": "Delivery",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(increase(mmmbbb_get_subscription_messages_num_delivered))",
     "legendFormat": "delivered"
    },
    {
     "expr": "sum(increase(mmmbbb_ack_deliveries_num_acked))",
     "legendFormat": "acked"
    },
    {
     "expr": "sum(increase(mmmbbb_deadletter_deliveries))",
     "legendFormat": "deadletter total"
    },
    {
     "expr": "sum(increase(mmmbbb_deadletter_deliveries_num_deadlettered))",
     "legendFormat": "deadletter bg"
    }
   ]
  },
  {
   "title": "HTTP Push",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(mmmbbb_http_push_duration_bucket)) by (le,outcome))",
     "legendFormat": "p95 {{outcome}}"
    },
    {
     "expr": "sum(increase(mmmbbb_http_push_duration_sum)) by (outcome) / sum(increase(mmmbbb_http_push_duration_count)) by (outcome)",
     "legendFormat": "per {{outcome}}"
    },
    {
     "expr": "sum(rate(mmmbbb_http_push_duration_count)) by (outcome)",
     "legendFormat": "rate {{outcome}}"
    }
   ]
  },
  {
   "title": "get msgs duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(mmmbbb_get_subscription_messages_duration_bucket)) by (le,outcome))",
     "legendFormat": "{{outcome}} 95%"
    },
    {
     "expr": "sum(increase(mmmbbb_get_subscription_messages_duration_sum)) by (outcome)",
     "legendFormat": "inc {{outcome}}"
    },
    {
     "expr": "sum(increase(mmmbbb_get_subscription_messages_duration_sum)) by (outcome) / sum(increase(mmmbbb_get_subscription_messages_duration_count)) by (outcome)",
     "legendFormat": "per {{outcome}}"
    }
   ]
  },
  {
   "title": "Pruned Rows",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum(increase(mmmbbb_prune_completed_deliveries_num_deleted))",
     "legendFormat": "delivs"
    },
    {
     "expr": "sum(increase(mmmbbb_prune_completed_messages_num_deleted))",
     "legendFormat": "msgs"
    },
    {
     "expr": "sum(increase(mmmbbb_prune_deleted_subscription_deliveries_num_deleted))",
     "legendFormat": "subs"
    },
    {
     "expr": "sum(increase(mmmbbb_prune_deleted_topics_num_deleted))",
     "legendFormat": "topics"
    }
   ]
  },
  {
   "title": "Total FC Wait",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(mmmbbb_message_streamer_flow_control_wait_sum))",
     "legendFormat": "wait time"
    }
   ]
  },
  {
   "title": "Pruning Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(mmmbbb_prune_completed_deliveries_duration_sum))",
     "legendFormat": "delivs"
    },
    {
     "expr": "sum(increase(mmmbbb_prune_completed_messages_duration_sum))",
     "legendFormat": "msgs"
    },
    {
     "expr": "sum(increase(mmmbbb_prune_deleted_subscription_deliveries_duration_sum))",
     "legendFormat": "subs"
    },
    {
     "expr": "sum(increase(mmmbbb_prune_deleted_topics_duration_sum))",
     "legendFormat": "topics"
    }
   ]
  },
  {
   "title": "Total Lock Wait",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(mmmbbb_get_subscription_messages_lock_wait_time_sum))"
    }
   ]
  },
  {
   "title": "Filtering",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "sum(increase(mmmbbb_delivery_suppressed)) by (reason)",
     "legendFormat": "deliv suppress {{reason}}"
    }
   ]
  }
 ]
}