#!/bin/sh

if [ -t 1 ]; then
	export MAGEFILE_ENABLE_COLOR=1
fi
if [ "$CI" -a "$1" = "-v" ]; then
	export VERBOSE=y
	# CI looks like a 48 core machine or such, but we only get access to a couple cores
	export GOMAXPROCS=4
fi
exec go run github.com/magefile/mage "$@"
