// Code generated by gen-types.sh. DO NOT EDIT.
package pubsubpb
import upstream "cloud.google.com/go/pubsub/v2/apiv1/pubsubpb"
type SchemaServiceClient = upstream.SchemaServiceClient
type SchemaServiceServer = upstream.SchemaServiceServer
type UnimplementedSchemaServiceServer = upstream.UnimplementedSchemaServiceServer
