// Code generated by gen-types.sh. DO NOT EDIT.
package pubsubpb
import upstream "cloud.google.com/go/pubsub/apiv1/pubsubpb"
type SchemaView = upstream.SchemaView
type Encoding = upstream.Encoding
type Schema_Type = upstream.Schema_Type
type Schema = upstream.Schema
type CreateSchemaRequest = upstream.CreateSchemaRequest
type GetSchemaRequest = upstream.GetSchemaRequest
type ListSchemasRequest = upstream.ListSchemasRequest
type ListSchemasResponse = upstream.ListSchemasResponse
type ListSchemaRevisionsRequest = upstream.ListSchemaRevisionsRequest
type ListSchemaRevisionsResponse = upstream.ListSchemaRevisionsResponse
type CommitSchemaRequest = upstream.CommitSchemaRequest
type RollbackSchemaRequest = upstream.RollbackSchemaRequest
type DeleteSchemaRevisionRequest = upstream.DeleteSchemaRevisionRequest
type DeleteSchemaRequest = upstream.DeleteSchemaRequest
type ValidateSchemaRequest = upstream.ValidateSchemaRequest
type ValidateSchemaResponse = upstream.ValidateSchemaResponse
type ValidateMessageRequest = upstream.ValidateMessageRequest
type ValidateMessageRequest_Name = upstream.ValidateMessageRequest_Name
type ValidateMessageRequest_Schema = upstream.ValidateMessageRequest_Schema
type ValidateMessageResponse = upstream.ValidateMessageResponse
