#!/usr/bin/env bash

# TODO: rewrite this as a go helper for portability

# FIXME: this is a dirty hack, see if there's a way to get protoc to do this
# natively

# without this, [A-Z] will be locale-sensitive and include lots of lower case
# letters
export LANG=C

{
	echo '// Code generated by gen-types.sh. DO NOT EDIT.'
	echo "package $1"
	echo "import upstream \"$2\""

	# generate a type alias for every exported type from the upstream package
	cat "$3" \
		| grep '^type [A-Z]' \
		| sed -e 's/^type \([^ ]*\) .*/type \1 = upstream.\1/'
} > "$4"
