// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"go.6river.tech/mmmbbb/ent/delivery"
	"go.6river.tech/mmmbbb/ent/message"
	"go.6river.tech/mmmbbb/ent/predicate"
	"go.6river.tech/mmmbbb/ent/topic"
)

// MessageUpdate is the builder for updating Message entities.
type MessageUpdate struct {
	config
	hooks    []Hook
	mutation *MessageMutation
}

// Where appends a list predicates to the MessageUpdate builder.
func (mu *MessageUpdate) Where(ps ...predicate.Message) *MessageUpdate {
	mu.mutation.Where(ps...)
	return mu
}

// SetTopicID sets the "topicID" field.
func (mu *MessageUpdate) SetTopicID(u uuid.UUID) *MessageUpdate {
	mu.mutation.SetTopicID(u)
	return mu
}

// SetNillableTopicID sets the "topicID" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableTopicID(u *uuid.UUID) *MessageUpdate {
	if u != nil {
		mu.SetTopicID(*u)
	}
	return mu
}

// AddDeliveryIDs adds the "deliveries" edge to the Delivery entity by IDs.
func (mu *MessageUpdate) AddDeliveryIDs(ids ...uuid.UUID) *MessageUpdate {
	mu.mutation.AddDeliveryIDs(ids...)
	return mu
}

// AddDeliveries adds the "deliveries" edges to the Delivery entity.
func (mu *MessageUpdate) AddDeliveries(d ...*Delivery) *MessageUpdate {
	ids := make([]uuid.UUID, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return mu.AddDeliveryIDs(ids...)
}

// SetTopic sets the "topic" edge to the Topic entity.
func (mu *MessageUpdate) SetTopic(t *Topic) *MessageUpdate {
	return mu.SetTopicID(t.ID)
}

// Mutation returns the MessageMutation object of the builder.
func (mu *MessageUpdate) Mutation() *MessageMutation {
	return mu.mutation
}

// ClearDeliveries clears all "deliveries" edges to the Delivery entity.
func (mu *MessageUpdate) ClearDeliveries() *MessageUpdate {
	mu.mutation.ClearDeliveries()
	return mu
}

// RemoveDeliveryIDs removes the "deliveries" edge to Delivery entities by IDs.
func (mu *MessageUpdate) RemoveDeliveryIDs(ids ...uuid.UUID) *MessageUpdate {
	mu.mutation.RemoveDeliveryIDs(ids...)
	return mu
}

// RemoveDeliveries removes "deliveries" edges to Delivery entities.
func (mu *MessageUpdate) RemoveDeliveries(d ...*Delivery) *MessageUpdate {
	ids := make([]uuid.UUID, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return mu.RemoveDeliveryIDs(ids...)
}

// ClearTopic clears the "topic" edge to the Topic entity.
func (mu *MessageUpdate) ClearTopic() *MessageUpdate {
	mu.mutation.ClearTopic()
	return mu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mu *MessageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, mu.sqlSave, mu.mutation, mu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mu *MessageUpdate) SaveX(ctx context.Context) int {
	affected, err := mu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mu *MessageUpdate) Exec(ctx context.Context) error {
	_, err := mu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mu *MessageUpdate) ExecX(ctx context.Context) {
	if err := mu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mu *MessageUpdate) check() error {
	if mu.mutation.TopicCleared() && len(mu.mutation.TopicIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Message.topic"`)
	}
	return nil
}

func (mu *MessageUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := mu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID))
	if ps := mu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if mu.mutation.AttributesCleared() {
		_spec.ClearField(message.FieldAttributes, field.TypeJSON)
	}
	if mu.mutation.OrderKeyCleared() {
		_spec.ClearField(message.FieldOrderKey, field.TypeString)
	}
	if mu.mutation.DeliveriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.DeliveriesTable,
			Columns: []string{message.DeliveriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(delivery.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.RemovedDeliveriesIDs(); len(nodes) > 0 && !mu.mutation.DeliveriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.DeliveriesTable,
			Columns: []string{message.DeliveriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(delivery.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.DeliveriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.DeliveriesTable,
			Columns: []string{message.DeliveriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(delivery.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if mu.mutation.TopicCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.TopicTable,
			Columns: []string{message.TopicColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(topic.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.TopicIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.TopicTable,
			Columns: []string{message.TopicColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(topic.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mu.mutation.done = true
	return n, nil
}

// MessageUpdateOne is the builder for updating a single Message entity.
type MessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MessageMutation
}

// SetTopicID sets the "topicID" field.
func (muo *MessageUpdateOne) SetTopicID(u uuid.UUID) *MessageUpdateOne {
	muo.mutation.SetTopicID(u)
	return muo
}

// SetNillableTopicID sets the "topicID" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableTopicID(u *uuid.UUID) *MessageUpdateOne {
	if u != nil {
		muo.SetTopicID(*u)
	}
	return muo
}

// AddDeliveryIDs adds the "deliveries" edge to the Delivery entity by IDs.
func (muo *MessageUpdateOne) AddDeliveryIDs(ids ...uuid.UUID) *MessageUpdateOne {
	muo.mutation.AddDeliveryIDs(ids...)
	return muo
}

// AddDeliveries adds the "deliveries" edges to the Delivery entity.
func (muo *MessageUpdateOne) AddDeliveries(d ...*Delivery) *MessageUpdateOne {
	ids := make([]uuid.UUID, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return muo.AddDeliveryIDs(ids...)
}

// SetTopic sets the "topic" edge to the Topic entity.
func (muo *MessageUpdateOne) SetTopic(t *Topic) *MessageUpdateOne {
	return muo.SetTopicID(t.ID)
}

// Mutation returns the MessageMutation object of the builder.
func (muo *MessageUpdateOne) Mutation() *MessageMutation {
	return muo.mutation
}

// ClearDeliveries clears all "deliveries" edges to the Delivery entity.
func (muo *MessageUpdateOne) ClearDeliveries() *MessageUpdateOne {
	muo.mutation.ClearDeliveries()
	return muo
}

// RemoveDeliveryIDs removes the "deliveries" edge to Delivery entities by IDs.
func (muo *MessageUpdateOne) RemoveDeliveryIDs(ids ...uuid.UUID) *MessageUpdateOne {
	muo.mutation.RemoveDeliveryIDs(ids...)
	return muo
}

// RemoveDeliveries removes "deliveries" edges to Delivery entities.
func (muo *MessageUpdateOne) RemoveDeliveries(d ...*Delivery) *MessageUpdateOne {
	ids := make([]uuid.UUID, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return muo.RemoveDeliveryIDs(ids...)
}

// ClearTopic clears the "topic" edge to the Topic entity.
func (muo *MessageUpdateOne) ClearTopic() *MessageUpdateOne {
	muo.mutation.ClearTopic()
	return muo
}

// Where appends a list predicates to the MessageUpdate builder.
func (muo *MessageUpdateOne) Where(ps ...predicate.Message) *MessageUpdateOne {
	muo.mutation.Where(ps...)
	return muo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (muo *MessageUpdateOne) Select(field string, fields ...string) *MessageUpdateOne {
	muo.fields = append([]string{field}, fields...)
	return muo
}

// Save executes the query and returns the updated Message entity.
func (muo *MessageUpdateOne) Save(ctx context.Context) (*Message, error) {
	return withHooks(ctx, muo.sqlSave, muo.mutation, muo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (muo *MessageUpdateOne) SaveX(ctx context.Context) *Message {
	node, err := muo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (muo *MessageUpdateOne) Exec(ctx context.Context) error {
	_, err := muo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (muo *MessageUpdateOne) ExecX(ctx context.Context) {
	if err := muo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (muo *MessageUpdateOne) check() error {
	if muo.mutation.TopicCleared() && len(muo.mutation.TopicIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Message.topic"`)
	}
	return nil
}

func (muo *MessageUpdateOne) sqlSave(ctx context.Context) (_node *Message, err error) {
	if err := muo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID))
	id, ok := muo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Message.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := muo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, message.FieldID)
		for _, f := range fields {
			if !message.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != message.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := muo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if muo.mutation.AttributesCleared() {
		_spec.ClearField(message.FieldAttributes, field.TypeJSON)
	}
	if muo.mutation.OrderKeyCleared() {
		_spec.ClearField(message.FieldOrderKey, field.TypeString)
	}
	if muo.mutation.DeliveriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.DeliveriesTable,
			Columns: []string{message.DeliveriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(delivery.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.RemovedDeliveriesIDs(); len(nodes) > 0 && !muo.mutation.DeliveriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.DeliveriesTable,
			Columns: []string{message.DeliveriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(delivery.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.DeliveriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   message.DeliveriesTable,
			Columns: []string{message.DeliveriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(delivery.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if muo.mutation.TopicCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.TopicTable,
			Columns: []string{message.TopicColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(topic.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.TopicIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   message.TopicTable,
			Columns: []string{message.TopicColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(topic.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Message{config: muo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, muo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	muo.mutation.done = true
	return _node, nil
}
