// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"go.6river.tech/mmmbbb/ent/predicate"
	"go.6river.tech/mmmbbb/ent/snapshot"
	"go.6river.tech/mmmbbb/ent/topic"
)

// SnapshotUpdate is the builder for updating Snapshot entities.
type SnapshotUpdate struct {
	config
	hooks    []Hook
	mutation *SnapshotMutation
}

// Where appends a list predicates to the SnapshotUpdate builder.
func (su *SnapshotUpdate) Where(ps ...predicate.Snapshot) *SnapshotUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetTopicID sets the "topicID" field.
func (su *SnapshotUpdate) SetTopicID(u uuid.UUID) *SnapshotUpdate {
	su.mutation.SetTopicID(u)
	return su
}

// SetNillableTopicID sets the "topicID" field if the given value is not nil.
func (su *SnapshotUpdate) SetNillableTopicID(u *uuid.UUID) *SnapshotUpdate {
	if u != nil {
		su.SetTopicID(*u)
	}
	return su
}

// SetExpiresAt sets the "expiresAt" field.
func (su *SnapshotUpdate) SetExpiresAt(t time.Time) *SnapshotUpdate {
	su.mutation.SetExpiresAt(t)
	return su
}

// SetNillableExpiresAt sets the "expiresAt" field if the given value is not nil.
func (su *SnapshotUpdate) SetNillableExpiresAt(t *time.Time) *SnapshotUpdate {
	if t != nil {
		su.SetExpiresAt(*t)
	}
	return su
}

// SetLabels sets the "labels" field.
func (su *SnapshotUpdate) SetLabels(m map[string]string) *SnapshotUpdate {
	su.mutation.SetLabels(m)
	return su
}

// ClearLabels clears the value of the "labels" field.
func (su *SnapshotUpdate) ClearLabels() *SnapshotUpdate {
	su.mutation.ClearLabels()
	return su
}

// SetAckedMessagesBefore sets the "ackedMessagesBefore" field.
func (su *SnapshotUpdate) SetAckedMessagesBefore(t time.Time) *SnapshotUpdate {
	su.mutation.SetAckedMessagesBefore(t)
	return su
}

// SetNillableAckedMessagesBefore sets the "ackedMessagesBefore" field if the given value is not nil.
func (su *SnapshotUpdate) SetNillableAckedMessagesBefore(t *time.Time) *SnapshotUpdate {
	if t != nil {
		su.SetAckedMessagesBefore(*t)
	}
	return su
}

// SetAckedMessageIDs sets the "ackedMessageIDs" field.
func (su *SnapshotUpdate) SetAckedMessageIDs(u []uuid.UUID) *SnapshotUpdate {
	su.mutation.SetAckedMessageIDs(u)
	return su
}

// AppendAckedMessageIDs appends u to the "ackedMessageIDs" field.
func (su *SnapshotUpdate) AppendAckedMessageIDs(u []uuid.UUID) *SnapshotUpdate {
	su.mutation.AppendAckedMessageIDs(u)
	return su
}

// ClearAckedMessageIDs clears the value of the "ackedMessageIDs" field.
func (su *SnapshotUpdate) ClearAckedMessageIDs() *SnapshotUpdate {
	su.mutation.ClearAckedMessageIDs()
	return su
}

// SetTopic sets the "topic" edge to the Topic entity.
func (su *SnapshotUpdate) SetTopic(t *Topic) *SnapshotUpdate {
	return su.SetTopicID(t.ID)
}

// Mutation returns the SnapshotMutation object of the builder.
func (su *SnapshotUpdate) Mutation() *SnapshotMutation {
	return su.mutation
}

// ClearTopic clears the "topic" edge to the Topic entity.
func (su *SnapshotUpdate) ClearTopic() *SnapshotUpdate {
	su.mutation.ClearTopic()
	return su
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SnapshotUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *SnapshotUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SnapshotUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SnapshotUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (su *SnapshotUpdate) check() error {
	if su.mutation.TopicCleared() && len(su.mutation.TopicIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Snapshot.topic"`)
	}
	return nil
}

func (su *SnapshotUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := su.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(snapshot.Table, snapshot.Columns, sqlgraph.NewFieldSpec(snapshot.FieldID, field.TypeUUID))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.ExpiresAt(); ok {
		_spec.SetField(snapshot.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := su.mutation.Labels(); ok {
		_spec.SetField(snapshot.FieldLabels, field.TypeJSON, value)
	}
	if su.mutation.LabelsCleared() {
		_spec.ClearField(snapshot.FieldLabels, field.TypeJSON)
	}
	if value, ok := su.mutation.AckedMessagesBefore(); ok {
		_spec.SetField(snapshot.FieldAckedMessagesBefore, field.TypeTime, value)
	}
	if value, ok := su.mutation.AckedMessageIDs(); ok {
		_spec.SetField(snapshot.FieldAckedMessageIDs, field.TypeJSON, value)
	}
	if value, ok := su.mutation.AppendedAckedMessageIDs(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, snapshot.FieldAckedMessageIDs, value)
		})
	}
	if su.mutation.AckedMessageIDsCleared() {
		_spec.ClearField(snapshot.FieldAckedMessageIDs, field.TypeJSON)
	}
	if su.mutation.TopicCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   snapshot.TopicTable,
			Columns: []string{snapshot.TopicColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(topic.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.TopicIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   snapshot.TopicTable,
			Columns: []string{snapshot.TopicColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(topic.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{snapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// SnapshotUpdateOne is the builder for updating a single Snapshot entity.
type SnapshotUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SnapshotMutation
}

// SetTopicID sets the "topicID" field.
func (suo *SnapshotUpdateOne) SetTopicID(u uuid.UUID) *SnapshotUpdateOne {
	suo.mutation.SetTopicID(u)
	return suo
}

// SetNillableTopicID sets the "topicID" field if the given value is not nil.
func (suo *SnapshotUpdateOne) SetNillableTopicID(u *uuid.UUID) *SnapshotUpdateOne {
	if u != nil {
		suo.SetTopicID(*u)
	}
	return suo
}

// SetExpiresAt sets the "expiresAt" field.
func (suo *SnapshotUpdateOne) SetExpiresAt(t time.Time) *SnapshotUpdateOne {
	suo.mutation.SetExpiresAt(t)
	return suo
}

// SetNillableExpiresAt sets the "expiresAt" field if the given value is not nil.
func (suo *SnapshotUpdateOne) SetNillableExpiresAt(t *time.Time) *SnapshotUpdateOne {
	if t != nil {
		suo.SetExpiresAt(*t)
	}
	return suo
}

// SetLabels sets the "labels" field.
func (suo *SnapshotUpdateOne) SetLabels(m map[string]string) *SnapshotUpdateOne {
	suo.mutation.SetLabels(m)
	return suo
}

// ClearLabels clears the value of the "labels" field.
func (suo *SnapshotUpdateOne) ClearLabels() *SnapshotUpdateOne {
	suo.mutation.ClearLabels()
	return suo
}

// SetAckedMessagesBefore sets the "ackedMessagesBefore" field.
func (suo *SnapshotUpdateOne) SetAckedMessagesBefore(t time.Time) *SnapshotUpdateOne {
	suo.mutation.SetAckedMessagesBefore(t)
	return suo
}

// SetNillableAckedMessagesBefore sets the "ackedMessagesBefore" field if the given value is not nil.
func (suo *SnapshotUpdateOne) SetNillableAckedMessagesBefore(t *time.Time) *SnapshotUpdateOne {
	if t != nil {
		suo.SetAckedMessagesBefore(*t)
	}
	return suo
}

// SetAckedMessageIDs sets the "ackedMessageIDs" field.
func (suo *SnapshotUpdateOne) SetAckedMessageIDs(u []uuid.UUID) *SnapshotUpdateOne {
	suo.mutation.SetAckedMessageIDs(u)
	return suo
}

// AppendAckedMessageIDs appends u to the "ackedMessageIDs" field.
func (suo *SnapshotUpdateOne) AppendAckedMessageIDs(u []uuid.UUID) *SnapshotUpdateOne {
	suo.mutation.AppendAckedMessageIDs(u)
	return suo
}

// ClearAckedMessageIDs clears the value of the "ackedMessageIDs" field.
func (suo *SnapshotUpdateOne) ClearAckedMessageIDs() *SnapshotUpdateOne {
	suo.mutation.ClearAckedMessageIDs()
	return suo
}

// SetTopic sets the "topic" edge to the Topic entity.
func (suo *SnapshotUpdateOne) SetTopic(t *Topic) *SnapshotUpdateOne {
	return suo.SetTopicID(t.ID)
}

// Mutation returns the SnapshotMutation object of the builder.
func (suo *SnapshotUpdateOne) Mutation() *SnapshotMutation {
	return suo.mutation
}

// ClearTopic clears the "topic" edge to the Topic entity.
func (suo *SnapshotUpdateOne) ClearTopic() *SnapshotUpdateOne {
	suo.mutation.ClearTopic()
	return suo
}

// Where appends a list predicates to the SnapshotUpdate builder.
func (suo *SnapshotUpdateOne) Where(ps ...predicate.Snapshot) *SnapshotUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SnapshotUpdateOne) Select(field string, fields ...string) *SnapshotUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Snapshot entity.
func (suo *SnapshotUpdateOne) Save(ctx context.Context) (*Snapshot, error) {
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SnapshotUpdateOne) SaveX(ctx context.Context) *Snapshot {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SnapshotUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SnapshotUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (suo *SnapshotUpdateOne) check() error {
	if suo.mutation.TopicCleared() && len(suo.mutation.TopicIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Snapshot.topic"`)
	}
	return nil
}

func (suo *SnapshotUpdateOne) sqlSave(ctx context.Context) (_node *Snapshot, err error) {
	if err := suo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(snapshot.Table, snapshot.Columns, sqlgraph.NewFieldSpec(snapshot.FieldID, field.TypeUUID))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Snapshot.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, snapshot.FieldID)
		for _, f := range fields {
			if !snapshot.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != snapshot.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.ExpiresAt(); ok {
		_spec.SetField(snapshot.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := suo.mutation.Labels(); ok {
		_spec.SetField(snapshot.FieldLabels, field.TypeJSON, value)
	}
	if suo.mutation.LabelsCleared() {
		_spec.ClearField(snapshot.FieldLabels, field.TypeJSON)
	}
	if value, ok := suo.mutation.AckedMessagesBefore(); ok {
		_spec.SetField(snapshot.FieldAckedMessagesBefore, field.TypeTime, value)
	}
	if value, ok := suo.mutation.AckedMessageIDs(); ok {
		_spec.SetField(snapshot.FieldAckedMessageIDs, field.TypeJSON, value)
	}
	if value, ok := suo.mutation.AppendedAckedMessageIDs(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, snapshot.FieldAckedMessageIDs, value)
		})
	}
	if suo.mutation.AckedMessageIDsCleared() {
		_spec.ClearField(snapshot.FieldAckedMessageIDs, field.TypeJSON)
	}
	if suo.mutation.TopicCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   snapshot.TopicTable,
			Columns: []string{snapshot.TopicColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(topic.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.TopicIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   snapshot.TopicTable,
			Columns: []string{snapshot.TopicColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(topic.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Snapshot{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{snapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
