// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"go.6river.tech/mmmbbb/ent/message"
	"go.6river.tech/mmmbbb/ent/predicate"
	"go.6river.tech/mmmbbb/ent/subscription"
	"go.6river.tech/mmmbbb/ent/topic"
)

// TopicUpdate is the builder for updating Topic entities.
type TopicUpdate struct {
	config
	hooks    []Hook
	mutation *TopicMutation
}

// Where appends a list predicates to the TopicUpdate builder.
func (_u *TopicUpdate) Where(ps ...predicate.Topic) *TopicUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetLive sets the "live" field.
func (_u *TopicUpdate) SetLive(v bool) *TopicUpdate {
	_u.mutation.SetLive(v)
	return _u
}

// SetNillableLive sets the "live" field if the given value is not nil.
func (_u *TopicUpdate) SetNillableLive(v *bool) *TopicUpdate {
	if v != nil {
		_u.SetLive(*v)
	}
	return _u
}

// ClearLive clears the value of the "live" field.
func (_u *TopicUpdate) ClearLive() *TopicUpdate {
	_u.mutation.ClearLive()
	return _u
}

// SetDeletedAt sets the "deletedAt" field.
func (_u *TopicUpdate) SetDeletedAt(v time.Time) *TopicUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deletedAt" field if the given value is not nil.
func (_u *TopicUpdate) SetNillableDeletedAt(v *time.Time) *TopicUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deletedAt" field.
func (_u *TopicUpdate) ClearDeletedAt() *TopicUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetLabels sets the "labels" field.
func (_u *TopicUpdate) SetLabels(v map[string]string) *TopicUpdate {
	_u.mutation.SetLabels(v)
	return _u
}

// ClearLabels clears the value of the "labels" field.
func (_u *TopicUpdate) ClearLabels() *TopicUpdate {
	_u.mutation.ClearLabels()
	return _u
}

// AddSubscriptionIDs adds the "subscriptions" edge to the Subscription entity by IDs.
func (_u *TopicUpdate) AddSubscriptionIDs(ids ...uuid.UUID) *TopicUpdate {
	_u.mutation.AddSubscriptionIDs(ids...)
	return _u
}

// AddSubscriptions adds the "subscriptions" edges to the Subscription entity.
func (_u *TopicUpdate) AddSubscriptions(v ...*Subscription) *TopicUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSubscriptionIDs(ids...)
}

// AddMessageIDs adds the "messages" edge to the Message entity by IDs.
func (_u *TopicUpdate) AddMessageIDs(ids ...uuid.UUID) *TopicUpdate {
	_u.mutation.AddMessageIDs(ids...)
	return _u
}

// AddMessages adds the "messages" edges to the Message entity.
func (_u *TopicUpdate) AddMessages(v ...*Message) *TopicUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMessageIDs(ids...)
}

// Mutation returns the TopicMutation object of the builder.
func (_u *TopicUpdate) Mutation() *TopicMutation {
	return _u.mutation
}

// ClearSubscriptions clears all "subscriptions" edges to the Subscription entity.
func (_u *TopicUpdate) ClearSubscriptions() *TopicUpdate {
	_u.mutation.ClearSubscriptions()
	return _u
}

// RemoveSubscriptionIDs removes the "subscriptions" edge to Subscription entities by IDs.
func (_u *TopicUpdate) RemoveSubscriptionIDs(ids ...uuid.UUID) *TopicUpdate {
	_u.mutation.RemoveSubscriptionIDs(ids...)
	return _u
}

// RemoveSubscriptions removes "subscriptions" edges to Subscription entities.
func (_u *TopicUpdate) RemoveSubscriptions(v ...*Subscription) *TopicUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSubscriptionIDs(ids...)
}

// ClearMessages clears all "messages" edges to the Message entity.
func (_u *TopicUpdate) ClearMessages() *TopicUpdate {
	_u.mutation.ClearMessages()
	return _u
}

// RemoveMessageIDs removes the "messages" edge to Message entities by IDs.
func (_u *TopicUpdate) RemoveMessageIDs(ids ...uuid.UUID) *TopicUpdate {
	_u.mutation.RemoveMessageIDs(ids...)
	return _u
}

// RemoveMessages removes "messages" edges to Message entities.
func (_u *TopicUpdate) RemoveMessages(v ...*Message) *TopicUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMessageIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TopicUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TopicUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TopicUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TopicUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *TopicUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(topic.Table, topic.Columns, sqlgraph.NewFieldSpec(topic.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Live(); ok {
		_spec.SetField(topic.FieldLive, field.TypeBool, value)
	}
	if _u.mutation.LiveCleared() {
		_spec.ClearField(topic.FieldLive, field.TypeBool)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(topic.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(topic.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Labels(); ok {
		_spec.SetField(topic.FieldLabels, field.TypeJSON, value)
	}
	if _u.mutation.LabelsCleared() {
		_spec.ClearField(topic.FieldLabels, field.TypeJSON)
	}
	if _u.mutation.SubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   topic.SubscriptionsTable,
			Columns: []string{topic.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSubscriptionsIDs(); len(nodes) > 0 && !_u.mutation.SubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   topic.SubscriptionsTable,
			Columns: []string{topic.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   topic.SubscriptionsTable,
			Columns: []string{topic.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   topic.MessagesTable,
			Columns: []string{topic.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !_u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   topic.MessagesTable,
			Columns: []string{topic.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   topic.MessagesTable,
			Columns: []string{topic.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{topic.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TopicUpdateOne is the builder for updating a single Topic entity.
type TopicUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TopicMutation
}

// SetLive sets the "live" field.
func (_u *TopicUpdateOne) SetLive(v bool) *TopicUpdateOne {
	_u.mutation.SetLive(v)
	return _u
}

// SetNillableLive sets the "live" field if the given value is not nil.
func (_u *TopicUpdateOne) SetNillableLive(v *bool) *TopicUpdateOne {
	if v != nil {
		_u.SetLive(*v)
	}
	return _u
}

// ClearLive clears the value of the "live" field.
func (_u *TopicUpdateOne) ClearLive() *TopicUpdateOne {
	_u.mutation.ClearLive()
	return _u
}

// SetDeletedAt sets the "deletedAt" field.
func (_u *TopicUpdateOne) SetDeletedAt(v time.Time) *TopicUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deletedAt" field if the given value is not nil.
func (_u *TopicUpdateOne) SetNillableDeletedAt(v *time.Time) *TopicUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deletedAt" field.
func (_u *TopicUpdateOne) ClearDeletedAt() *TopicUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetLabels sets the "labels" field.
func (_u *TopicUpdateOne) SetLabels(v map[string]string) *TopicUpdateOne {
	_u.mutation.SetLabels(v)
	return _u
}

// ClearLabels clears the value of the "labels" field.
func (_u *TopicUpdateOne) ClearLabels() *TopicUpdateOne {
	_u.mutation.ClearLabels()
	return _u
}

// AddSubscriptionIDs adds the "subscriptions" edge to the Subscription entity by IDs.
func (_u *TopicUpdateOne) AddSubscriptionIDs(ids ...uuid.UUID) *TopicUpdateOne {
	_u.mutation.AddSubscriptionIDs(ids...)
	return _u
}

// AddSubscriptions adds the "subscriptions" edges to the Subscription entity.
func (_u *TopicUpdateOne) AddSubscriptions(v ...*Subscription) *TopicUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSubscriptionIDs(ids...)
}

// AddMessageIDs adds the "messages" edge to the Message entity by IDs.
func (_u *TopicUpdateOne) AddMessageIDs(ids ...uuid.UUID) *TopicUpdateOne {
	_u.mutation.AddMessageIDs(ids...)
	return _u
}

// AddMessages adds the "messages" edges to the Message entity.
func (_u *TopicUpdateOne) AddMessages(v ...*Message) *TopicUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMessageIDs(ids...)
}

// Mutation returns the TopicMutation object of the builder.
func (_u *TopicUpdateOne) Mutation() *TopicMutation {
	return _u.mutation
}

// ClearSubscriptions clears all "subscriptions" edges to the Subscription entity.
func (_u *TopicUpdateOne) ClearSubscriptions() *TopicUpdateOne {
	_u.mutation.ClearSubscriptions()
	return _u
}

// RemoveSubscriptionIDs removes the "subscriptions" edge to Subscription entities by IDs.
func (_u *TopicUpdateOne) RemoveSubscriptionIDs(ids ...uuid.UUID) *TopicUpdateOne {
	_u.mutation.RemoveSubscriptionIDs(ids...)
	return _u
}

// RemoveSubscriptions removes "subscriptions" edges to Subscription entities.
func (_u *TopicUpdateOne) RemoveSubscriptions(v ...*Subscription) *TopicUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSubscriptionIDs(ids...)
}

// ClearMessages clears all "messages" edges to the Message entity.
func (_u *TopicUpdateOne) ClearMessages() *TopicUpdateOne {
	_u.mutation.ClearMessages()
	return _u
}

// RemoveMessageIDs removes the "messages" edge to Message entities by IDs.
func (_u *TopicUpdateOne) RemoveMessageIDs(ids ...uuid.UUID) *TopicUpdateOne {
	_u.mutation.RemoveMessageIDs(ids...)
	return _u
}

// RemoveMessages removes "messages" edges to Message entities.
func (_u *TopicUpdateOne) RemoveMessages(v ...*Message) *TopicUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMessageIDs(ids...)
}

// Where appends a list predicates to the TopicUpdate builder.
func (_u *TopicUpdateOne) Where(ps ...predicate.Topic) *TopicUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TopicUpdateOne) Select(field string, fields ...string) *TopicUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Topic entity.
func (_u *TopicUpdateOne) Save(ctx context.Context) (*Topic, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TopicUpdateOne) SaveX(ctx context.Context) *Topic {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TopicUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TopicUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *TopicUpdateOne) sqlSave(ctx context.Context) (_node *Topic, err error) {
	_spec := sqlgraph.NewUpdateSpec(topic.Table, topic.Columns, sqlgraph.NewFieldSpec(topic.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Topic.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, topic.FieldID)
		for _, f := range fields {
			if !topic.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != topic.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Live(); ok {
		_spec.SetField(topic.FieldLive, field.TypeBool, value)
	}
	if _u.mutation.LiveCleared() {
		_spec.ClearField(topic.FieldLive, field.TypeBool)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(topic.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(topic.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Labels(); ok {
		_spec.SetField(topic.FieldLabels, field.TypeJSON, value)
	}
	if _u.mutation.LabelsCleared() {
		_spec.ClearField(topic.FieldLabels, field.TypeJSON)
	}
	if _u.mutation.SubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   topic.SubscriptionsTable,
			Columns: []string{topic.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSubscriptionsIDs(); len(nodes) > 0 && !_u.mutation.SubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   topic.SubscriptionsTable,
			Columns: []string{topic.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   topic.SubscriptionsTable,
			Columns: []string{topic.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   topic.MessagesTable,
			Columns: []string{topic.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !_u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   topic.MessagesTable,
			Columns: []string{topic.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   topic.MessagesTable,
			Columns: []string{topic.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Topic{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{topic.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
